package store

const mysqlSchema = `
CREATE TABLE IF NOT EXISTS PHASEDB_HISTORY (
    ID                BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MIGRATION_NAME    VARCHAR(256) NOT NULL,
    PHASE_NAME        VARCHAR(64)  NOT NULL,
    ATTEMPT_NUMBER    INT UNSIGNED NOT NULL,
    EVENT_TYPE        ENUM('PHASE_STARTED','PHASE_COMPLETED','PHASE_FAILED',
                           'PHASE_TIMED_OUT','PHASE_SKIPPED','PHASE_ROLLED_BACK') NOT NULL,
    PHASE_TYPE        ENUM('EXPAND','BACKFILL','GATE','CONTRACT') NOT NULL,
    PHASE_CONFIG_JSON TEXT NOT NULL,
    ROWS_AFFECTED     BIGINT NULL,
    ERROR_MESSAGE     TEXT NULL,
    INSTALLED_BY      VARCHAR(256) NOT NULL,
    PHASEDB_VERSION   VARCHAR(32)  NOT NULL,
    CREATED_AT        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_attempt_event (MIGRATION_NAME, PHASE_NAME, ATTEMPT_NUMBER, EVENT_TYPE),
    KEY idx_latest (MIGRATION_NAME, PHASE_NAME, ID DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PHASEDB_CHECKPOINTS (
    ID               BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MIGRATION_NAME   VARCHAR(256) NOT NULL,
    PHASE_NAME       VARCHAR(64)  NOT NULL,
    ATTEMPT_NUMBER   INT UNSIGNED NOT NULL,
    STATEMENT_INDEX  INT UNSIGNED NOT NULL DEFAULT 0,
    CHECKPOINT_JSON  TEXT NOT NULL,
    CREATED_AT       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_resume (MIGRATION_NAME, PHASE_NAME, ATTEMPT_NUMBER, ID DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PHASEDB_HEARTBEATS (
    ID               BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MIGRATION_NAME   VARCHAR(256) NOT NULL,
    PHASE_NAME       VARCHAR(64)  NOT NULL,
    ATTEMPT_NUMBER   INT UNSIGNED NOT NULL,
    PROCESS_ID       VARCHAR(512) NOT NULL,
    CREATED_AT       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_liveness (MIGRATION_NAME, PHASE_NAME, ATTEMPT_NUMBER, CREATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PHASEDB_LOCKS (
    MIGRATION_NAME   VARCHAR(256) PRIMARY KEY,
    PROCESS_ID       VARCHAR(512) NOT NULL,
    ACQUIRED_AT      DATETIME(3)  NOT NULL,
    EXPIRES_AT       DATETIME(3)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`
